#!/usr/bin/env python3
"""Deterministic merge, fingerprint, and redaction for Ape Context artifacts."""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
import sys
import tempfile
from pathlib import Path
from typing import Any


ENTERPRISE_HEADING = "## Enterprise Context"
GENERATED_MARKER = "<!-- generated by context-instructions -->"
SENSITIVE_NAME = re.compile(
    r"(?i)(secret|token|password|passwd|pwd|api[_-]?key|private[_-]?key|"
    r"client[_-]?secret|credential|bearer|account[_-]?key)"
)
PLACEHOLDER = re.compile(
    r"^(?:\$\{[^}]+\}|%[A-Za-z_][A-Za-z0-9_]*%|"
    r"<[^>]+>|your[-_ ].+|\[REDACTED\])$",
    re.IGNORECASE,
)


class ArtifactError(RuntimeError):
    """Raised when an artifact cannot be handled safely."""


def read_text(path: Path) -> str:
    try:
        return path.read_bytes().decode("utf-8")
    except FileNotFoundError as exc:
        raise ArtifactError(f"file not found: {path}") from exc
    except UnicodeDecodeError as exc:
        raise ArtifactError(f"file is not valid UTF-8: {path}") from exc


def atomic_write(path: Path, content: str, mode: int | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, temp_name = tempfile.mkstemp(prefix=f".{path.name}.", dir=path.parent)
    temp_path = Path(temp_name)
    try:
        with os.fdopen(fd, "wb") as handle:
            handle.write(content.encode("utf-8"))
            handle.flush()
            os.fsync(handle.fileno())
        if mode is not None:
            os.chmod(temp_path, stat.S_IMODE(mode))
        os.replace(temp_path, path)
    finally:
        temp_path.unlink(missing_ok=True)


def detect_newline(text: str) -> str:
    return "\r\n" if "\r\n" in text else "\n"


def normalize_section(section: str) -> str:
    lines = section.replace("\r\n", "\n").replace("\r", "\n").split("\n")
    normalized = "\n".join(line.rstrip(" \t") for line in lines).rstrip("\n")
    return f"{normalized}\n"


def validate_generated_section(section: str) -> str:
    normalized = normalize_section(section)
    first_line = normalized.splitlines()[0] if normalized else ""
    if first_line != ENTERPRISE_HEADING:
        raise ArtifactError(f"section must start with {ENTERPRISE_HEADING!r}")
    if GENERATED_MARKER not in normalized:
        raise ArtifactError(f"section must contain {GENERATED_MARKER!r}")
    return normalized


def enterprise_span(text: str) -> tuple[int, int] | None:
    heading = re.search(r"(?m)^## Enterprise Context[ \t]*\r?$", text)
    if not heading:
        return None
    next_heading = re.search(r"(?m)^## (?!Enterprise Context[ \t]*\r?$).+", text[heading.end() :])
    end = heading.end() + next_heading.start() if next_heading else len(text)
    return heading.start(), end


def merge_enterprise_context(
    existing: str | None,
    section: str,
    *,
    allow_manual: bool = False,
) -> tuple[str, str]:
    generated = validate_generated_section(section)
    if existing is None:
        return generated, "create"

    newline = detect_newline(existing)
    rendered = generated.replace("\n", newline)
    span = enterprise_span(existing)
    if span is None:
        separator = "" if not existing else ("" if existing.endswith(("\n", "\r")) else newline)
        if existing and not existing.endswith((newline * 2,)):
            separator += newline
        return f"{existing}{separator}{rendered}", "append"

    start, end = span
    current = existing[start:end]
    if GENERATED_MARKER not in current and not allow_manual:
        raise ArtifactError(
            "manual Enterprise Context detected; explicit --allow-manual approval required"
        )

    suffix = existing[end:]
    if suffix and not rendered.endswith(newline * 2):
        rendered = rendered.rstrip("\r\n") + newline * 2
    return f"{existing[:start]}{rendered}{suffix}", "replace"


def extract_enterprise_context(text: str) -> str:
    span = enterprise_span(text)
    if span is None:
        raise ArtifactError(f"{ENTERPRISE_HEADING!r} section not found")
    return text[span[0] : span[1]]


def fingerprint(text: str) -> str:
    normalized = normalize_section(extract_enterprise_context(text))
    return f"sha256:{hashlib.sha256(normalized.encode('utf-8')).hexdigest()}"


def is_secret_value(value: Any) -> bool:
    if not isinstance(value, str):
        return False
    stripped = value.strip()
    return len(stripped) >= 4 and not PLACEHOLDER.match(stripped)


def collect_named_secrets(value: Any, secrets: set[str], key: str = "") -> None:
    if isinstance(value, dict):
        for child_key, child_value in value.items():
            if SENSITIVE_NAME.search(str(child_key)) and is_secret_value(child_value):
                secrets.add(str(child_value))
            collect_named_secrets(child_value, secrets, str(child_key))
    elif isinstance(value, list):
        for child in value:
            collect_named_secrets(child, secrets, key)
    elif SENSITIVE_NAME.search(key) and is_secret_value(value):
        secrets.add(str(value))


def known_secrets(mcp_config: Path | None) -> set[str]:
    secrets = {
        value
        for name, value in os.environ.items()
        if SENSITIVE_NAME.search(name) and is_secret_value(value)
    }
    if mcp_config and mcp_config.exists():
        try:
            collect_named_secrets(json.loads(read_text(mcp_config)), secrets)
        except json.JSONDecodeError as exc:
            raise ArtifactError(f"invalid JSON in {mcp_config}: {exc}") from exc
    return secrets


def redact(text: str, secrets: set[str]) -> str:
    redacted = text
    for secret in sorted(secrets, key=len, reverse=True):
        redacted = redacted.replace(secret, "[REDACTED]")

    patterns = [
        (
            re.compile(
                r'(?i)(["\']?(?:api[_-]?key|token|secret|password|passwd|pwd|'
                r'client[_-]?secret|private[_-]?key|credential|account[_-]?key)'
                r'["\']?\s*[:=]\s*)(["\']?)(?!\[REDACTED\])([^"\'\s,;]+)(["\']?)'
            ),
            r"\1\2[REDACTED]\4",
        ),
        (re.compile(r"(?i)\bBearer\s+[A-Za-z0-9._~+/=-]{8,}"), "Bearer [REDACTED]"),
        (
            re.compile(r"\b(?:gh[pousr]_[A-Za-z0-9_]{16,}|github_pat_[A-Za-z0-9_]{16,})\b"),
            "[REDACTED]",
        ),
        (
            re.compile(
                r"\beyJ[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\.[A-Za-z0-9_-]{8,}\b"
            ),
            "[REDACTED]",
        ),
    ]
    for pattern, replacement in patterns:
        redacted = pattern.sub(replacement, redacted)

    leaked = [secret for secret in secrets if secret and secret in redacted]
    if leaked:
        raise ArtifactError("sanitization failed: known secret remains in output")
    return redacted


def merge_command(args: argparse.Namespace) -> int:
    target = Path(args.target)
    existing = read_text(target) if target.exists() else None
    section = read_text(Path(args.section_file))
    result, mode = merge_enterprise_context(
        existing, section, allow_manual=args.allow_manual
    )
    if args.dry_run:
        sys.stdout.write(result)
    else:
        existing_mode = target.stat().st_mode if target.exists() else None
        atomic_write(target, result, existing_mode)
        print(json.dumps({"mode": mode, "target": str(target)}))
    return 0


def fingerprint_command(args: argparse.Namespace) -> int:
    print(fingerprint(read_text(Path(args.target))))
    return 0


def sanitize_command(args: argparse.Namespace) -> int:
    source = Path(args.input)
    result = redact(read_text(source), known_secrets(Path(args.mcp_config) if args.mcp_config else None))
    if args.dry_run:
        sys.stdout.write(result)
    else:
        output = Path(args.output)
        output_mode = output.stat().st_mode if output.exists() else None
        atomic_write(output, result, output_mode)
        print(json.dumps({"output": str(output), "redacted": result.count("[REDACTED]")}))
    return 0


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(description=__doc__)
    commands = root.add_subparsers(dest="command", required=True)

    merge = commands.add_parser("merge", help="merge generated Enterprise Context")
    merge.add_argument("--target", required=True)
    merge.add_argument("--section-file", required=True)
    merge.add_argument("--allow-manual", action="store_true")
    merge.add_argument("--dry-run", action="store_true")
    merge.set_defaults(handler=merge_command)

    digest = commands.add_parser("fingerprint", help="fingerprint Enterprise Context")
    digest.add_argument("--target", required=True)
    digest.set_defaults(handler=fingerprint_command)

    sanitize = commands.add_parser("sanitize", help="redact report content")
    sanitize.add_argument("--input", required=True)
    sanitize.add_argument("--output")
    sanitize.add_argument("--mcp-config")
    sanitize.add_argument("--dry-run", action="store_true")
    sanitize.set_defaults(handler=sanitize_command)

    return root


def main() -> int:
    args = parser().parse_args()
    if args.command == "sanitize" and not args.dry_run and not args.output:
        raise ArtifactError("--output is required unless --dry-run is used")
    try:
        return args.handler(args)
    except ArtifactError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
