import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = ROOT / ".github" / "scripts" / "context_artifacts.py"


class ContextArtifactsTest(unittest.TestCase):
    def run_cli(self, *args: str, env: dict[str, str] | None = None) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            [sys.executable, str(SCRIPT), *args],
            cwd=ROOT,
            env=env,
            text=True,
            capture_output=True,
            check=False,
        )

    def generated_section(self) -> str:
        return (
            "## Enterprise Context\n"
            "<!-- generated by context-instructions -->\n"
            "New generated context.\n"
        )

    def test_create_append_and_replace_preserve_surrounding_content(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            section = root / "section.md"
            section.write_text(self.generated_section(), encoding="utf-8")

            created = root / "created.md"
            result = self.run_cli(
                "merge", "--target", str(created), "--section-file", str(section)
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertEqual(created.read_text(encoding="utf-8"), self.generated_section())

            appended = root / "appended.md"
            prefix = "# Copilot Instructions\n\n## Coding Style\nKeep tests fast.\n"
            appended.write_text(prefix, encoding="utf-8")
            dry_run = self.run_cli(
                "merge",
                "--target",
                str(appended),
                "--section-file",
                str(section),
                "--dry-run",
            )
            self.assertEqual(dry_run.returncode, 0, dry_run.stderr)
            self.assertIn("New generated context.", dry_run.stdout)
            self.assertEqual(appended.read_text(encoding="utf-8"), prefix)

            result = self.run_cli(
                "merge", "--target", str(appended), "--section-file", str(section)
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            appended_text = appended.read_text(encoding="utf-8")
            self.assertTrue(appended_text.startswith(prefix))
            self.assertIn(self.generated_section(), appended_text)

            replaced = root / "replaced.md"
            suffix = "## Local Rules\nUse pytest for Python tests.\n"
            replaced.write_text(
                "# Copilot Instructions\n\n"
                "## Enterprise Context\n"
                "<!-- generated by context-instructions -->\n"
                "Old generated context.\n\n"
                + suffix,
                encoding="utf-8",
            )
            result = self.run_cli(
                "merge", "--target", str(replaced), "--section-file", str(section)
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            replaced_text = replaced.read_text(encoding="utf-8")
            self.assertIn("New generated context.", replaced_text)
            self.assertNotIn("Old generated context.", replaced_text)
            self.assertTrue(replaced_text.endswith(suffix))

    def test_manual_section_requires_explicit_override(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            target = root / "instructions.md"
            section = root / "section.md"
            target.write_text(
                "## Enterprise Context\nHuman-authored context.\n", encoding="utf-8"
            )
            section.write_text(self.generated_section(), encoding="utf-8")

            blocked = self.run_cli(
                "merge", "--target", str(target), "--section-file", str(section)
            )
            self.assertEqual(blocked.returncode, 2)
            self.assertIn("--allow-manual", blocked.stderr)
            self.assertIn("Human-authored context.", target.read_text(encoding="utf-8"))

            allowed = self.run_cli(
                "merge",
                "--target",
                str(target),
                "--section-file",
                str(section),
                "--allow-manual",
            )
            self.assertEqual(allowed.returncode, 0, allowed.stderr)
            self.assertNotIn("Human-authored context.", target.read_text(encoding="utf-8"))

    def test_fingerprint_normalizes_line_endings_and_trailing_space(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            first = root / "first.md"
            second = root / "second.md"
            first.write_bytes(
                b"## Enterprise Context\r\n"
                b"<!-- generated by context-instructions -->\r\n"
                b"Rule.   \r\n"
            )
            second.write_text(
                "## Enterprise Context\n"
                "<!-- generated by context-instructions -->\n"
                "Rule.\n",
                encoding="utf-8",
            )
            one = self.run_cli("fingerprint", "--target", str(first))
            two = self.run_cli("fingerprint", "--target", str(second))
            self.assertEqual(one.returncode, 0, one.stderr)
            self.assertEqual(two.returncode, 0, two.stderr)
            self.assertEqual(one.stdout, two.stdout)
            self.assertRegex(one.stdout.strip(), r"^sha256:[0-9a-f]{64}$")

    def test_sanitize_redacts_known_and_structured_secrets(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            draft = root / "draft.md"
            output = root / "report.md"
            config = root / "mcp.json"
            secret = "actual-secret-value-123"
            config.write_text(
                json.dumps({"mcpServers": {"example": {"env": {"API_TOKEN": secret}}}}),
                encoding="utf-8",
            )
            draft.write_text(
                "# Report\n"
                f"API_TOKEN={secret}\n"
                '\"password\": \"another-password-value\"\n'
                "Authorization: Bearer abcdefghijklmnop\n"
                "GitHub: ghp_abcdefghijklmnopqrstuvwx\n",
                encoding="utf-8",
            )
            env = os.environ.copy()
            env["CLIENT_SECRET"] = "environment-secret-value"
            draft.write_text(
                draft.read_text(encoding="utf-8")
                + "CLIENT_SECRET=environment-secret-value\n",
                encoding="utf-8",
            )

            result = self.run_cli(
                "sanitize",
                "--input",
                str(draft),
                "--output",
                str(output),
                "--mcp-config",
                str(config),
                env=env,
            )
            self.assertEqual(result.returncode, 0, result.stderr)
            self.assertNotIn(secret, result.stdout)
            self.assertNotIn(secret, result.stderr)
            self.assertNotIn("environment-secret-value", result.stdout)
            self.assertNotIn("environment-secret-value", result.stderr)
            sanitized = output.read_text(encoding="utf-8")
            self.assertNotIn(secret, sanitized)
            self.assertNotIn("another-password-value", sanitized)
            self.assertNotIn("abcdefghijklmnop", sanitized)
            self.assertNotIn("environment-secret-value", sanitized)
            self.assertIn("API_TOKEN=[REDACTED]", sanitized)
            self.assertGreaterEqual(sanitized.count("[REDACTED]"), 5)


if __name__ == "__main__":
    unittest.main()
